
*************************************************************
********          Set Working Directory           ***********
*************************************************************

#Insert WD below (line 10)
#Use path: "...\01_Data"
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "")   #Enter WD here! (Windows: change \ to /)
getwd()
st=format(Sys.time(), "%d-%m-%Y_%H_%M")
```

#Install packages
```{r include=FALSE}
if (!require(tidyverse)) {install.packages("tidyverse")}
library(tidyverse)
if (!require(ROAuth)) {install.packages("ROAuth")}
library(ROAuth)
if(!require(tm)) {install.packages("tm")}
library(tm)
if(!require(wordcloud)) {install.packages("wordcloud")}
library(wordcloud)
if(!require(htmlwidgets)) {install.packages("htmlwidgets")}
library(htmlwidgets)
if(!require(wordcloud2)) {install.packages("wordcloud2")}
library(wordcloud2)
if(!require(data.table)) {install.packages("data.table")}
library(data.table)
if(!require(lubridate)) {install.packages("lubridate")}
library(lubridate)
if(!require(igraph)) {install.packages("igraph")}
library(igraph)
if (!require(readstata13)) {install.packages("readstata13")}
library(readstata13)
if (!require(RColorBrewer)) {install.packages("RColorBrewer")}
library(RColorBrewer)
```



*************************************************************
********   Information from Deal-Description     ***********
*************************************************************

#Read data
```{r}
mydata <- read.dta13("./05_OTHER/SDC_COMPUSTAT_DEALTEXT_RAW.dta") 
newdata <- mydata
```

#Generate Word-Cloud
```{r include=FALSE}
dealtext <- newdata$DEALTEXT
deal.text <- gettext(dealtext)
modi <- Corpus(VectorSource(deal.text))
#inspect(modi)[1:1]

#Prep2: Remove certain words
modi <- tm_map(modi,stripWhitespace)
modi <- tm_map(modi, content_transformer(tolower))
modi <- tm_map(modi,removeNumbers)
modi <- tm_map(modi,removePunctuation)
modi <- tm_map(modi,removeWords, stopwords("english"))
modi <- tm_map(modi,removeWords, c("and","the","our","that","for","are","also","more","has","must","have","should","this","with", "joint", "venture", "strategic", "alliance", "ltd", "corp", "group", "named", "terms", "states", "formed", "inc", "china", "could", "provide", "mil", "will", "disclosed", "signed", "microsoft", "entered", "details", "ibm", "agreement", "unit", "united"))
modi <- tm_map(modi, stripWhitespace)

#Worldcloud
png("./06_OUTPUT/01_FIG/04_WORDCLOUD_DEALTEXT.png", width=1000,height=1000)
wordcloud(modi, scale=c(12,0.2), max.words=50, random.order=FALSE, rot.per=0.3, use.r.layout=FALSE, colors=brewer.pal(8, "Dark2"))
```

#Create Dummies for main business purpose of a network
  #taken from wordcloud
  #business purposes are: development, licensing, services, marketing, wholesale, supply 
```{r}
#wholesale
newdata <- mutate(newdata, purpose_wholesale = 0)
newdata$purpose_wholesale[grepl("wholesale", newdata$DEALTEXT, ignore.case = TRUE)] <- 1

#development
newdata <- mutate(newdata, purpose_develop = 0)
newdata$purpose_develop[grepl("develop", newdata$DEALTEXT, ignore.case = TRUE)] <- 1
newdata$purpose_develop[grepl("research", newdata$DEALTEXT, ignore.case = TRUE)] <- 1

#licensing
newdata <- mutate(newdata, purpose_license = 0)
newdata$purpose_license[grepl("licens", newdata$DEALTEXT, ignore.case = TRUE)] <- 1

#services
newdata <- mutate(newdata, purpose_service = 0)
newdata$purpose_service[grepl("service", newdata$DEALTEXT, ignore.case = FALSE)] <- 1

#marketing
newdata <- mutate(newdata, purpose_marketing = 0)
newdata$purpose_marketing[grepl("marketing", newdata$DEALTEXT, ignore.case = TRUE)] <- 1

#marketing
newdata <- mutate(newdata, purpose_marketing = 0)
newdata$purpose_marketing[grepl("marketing", newdata$DEALTEXT, ignore.case = TRUE)] <- 1

#supply
newdata <- mutate(newdata, purpose_supply = 0)
newdata$purpose_supply[grepl("supply", newdata$DEALTEXT, ignore.case = TRUE)] <- 1

#manufacture
newdata <- mutate(newdata, purpose_manufacture = 0)
newdata$purpose_manufacture[grepl("manufactur", newdata$DEALTEXT, ignore.case = TRUE)] <- 1

#Save
save.dta13(newdata, "./05_OTHER/SDC_COMPUSTAT_DEALTEXT_PROCESSED.dta")
```



*************************************************************
********           Create a Network Map           ***********
*************************************************************

#Network Map
```{r}
#Load data:
links <- read.dta13("./05_OTHER/SDC_COMPUSTAT_NETWORK_RAW1.dta") 
nodes <- read.dta13("./05_OTHER/SDC_COMPUSTAT_NETWORK_RAW2.dta")
nodes <- nodes[c(2,1)]

#Turn it into igraph object
network <- graph_from_data_frame(d=links, vertices = nodes, directed=F) 
 
#Make a palette of colors
a <- c("gray", "black")
coul <- as.character(a)
 
#Create a vector of color
my_color <- coul[as.numeric(as.factor(V(network)$LOWTAX))]

#Make the plot
png("./06_OUTPUT/01_FIG/03_NETWORKMAP.png", width=2000,height=2000)
plot(network, vertex.size=2.5, vertex.label=NA, layout=layout_nicely, vertex.shape="csquare", vertex.color=my_color)
```

#Clear environment
```{r include=FALSE}
rm(list = ls())
gc()
```
